import XCTest
@testable import Prvital

/// Tests for the format-detecting external importer (`ExternalCSVImporter`):
/// header detection for Dexcom Clarity / LibreView / Prvital exports, and the
/// pure row decoding into `ParsedRow`. No SwiftData is touched here.
final class ExternalCSVImporterTests: XCTestCase {

    // MARK: Sample documents

    private let clarityMgdl = """
    Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mg/dL),Insulin Value (u),Carb Value (grams),Duration (hh:mm:ss),Glucose Rate of Change (mg/dL/min),Transmitter Time (Long Integer),Transmitter ID
    1,,FirstName,,Jane
    2,,LastName,,Doe
    3,,Device,,,Dexcom G6 Mobile App,iPhone G6
    4,,Alert,High,,,,200
    5,2024-06-01T08:03:12,EGV,,,,iPhone G6,124
    6,2024-06-01T08:08:12,EGV,,,,iPhone G6,131
    7,2024-06-01T12:00:00,Insulin,Fast-Acting,,,,,4.5
    8,2024-06-01T22:00:00,Insulin,Long-Acting,,,,,18.0
    9,2024-06-01T12:30:00,Carbs,,,,,,,45
    10,2024-06-01T09:00:00,Calibration,,,,iPhone G6,118
    """

    private let clarityMmol = """
    Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mmol/L),Insulin Value (u),Carb Value (grams),Duration (hh:mm:ss),Glucose Rate of Change (mmol/L/min),Transmitter Time (Long Integer),Transmitter ID
    1,2024-06-01T08:03:12,EGV,,,,iPhone G6,6.9
    """

    private let clarityWithClamps = """
    Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mg/dL),Insulin Value (u),Carb Value (grams),Duration (hh:mm:ss),Glucose Rate of Change (mg/dL/min),Transmitter Time (Long Integer),Transmitter ID
    1,2024-06-01T03:00:00,EGV,,,,iPhone G6,Low
    2,2024-06-01T03:05:00,EGV,,,,iPhone G6,High
    3,2024-06-01T03:10:00,EGV,,,,iPhone G6,250
    """

    /// US-region LibreView export: 12-hour "MM-dd-yyyy hh:mm a" timestamps.
    /// Covers historic (0), scan (1), strip (2), insulin (4) rapid + long,
    /// food (5) and a notes row (6) that must count as skipped.
    private let libreViewUS = """
    Glucose Data,Generated on,06-10-2024 10:57 AM UTC,Generated by,Jane Doe
    Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
    FreeStyle Libre 3,ABC123,06-01-2024 08:04 AM,0,101
    FreeStyle Libre 3,ABC123,06-01-2024 08:19 AM,0,105
    FreeStyle Libre 3,ABC123,06-01-2024 08:30 AM,1,,112
    FreeStyle Libre 3,ABC123,06-01-2024 12:15 PM,4,,,,6.5
    FreeStyle Libre 3,ABC123,06-01-2024 10:00 PM,4,,,,,,,,,22
    FreeStyle Libre 3,ABC123,06-01-2024 12:20 PM,5,,,,,,52
    FreeStyle Libre 3,ABC123,06-01-2024 07:45 AM,2,,,,,,,,,,,98
    FreeStyle Libre 3,ABC123,06-01-2024 01:00 PM,6,,,,,,,,,,Walked the dog
    """

    /// EU-region LibreView export: 24-hour "dd-MM-yyyy HH:mm" timestamps and
    /// mmol/L glucose columns. The 13-06 row can only be day-month, which
    /// forces the whole document onto the EU pattern.
    private let libreViewEU = """
    Glucose Data,Generated on,10-06-2024 10:57 UTC,Generated by,Jane Doe
    Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mmol/L,Scan Glucose mmol/L,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mmol/L,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
    FreeStyle Libre 3,ABC123,01-06-2024 08:15,0,6.1
    FreeStyle Libre 3,ABC123,13-06-2024 14:19,1,,7.2
    """

    private let prvitalCSV = """
    record_type,timestamp_utc,source,value,unit,detail
    glucose,2024-06-01T08:00:00Z,Manual entry,124,mg/dL,Sensor
    """

    // MARK: Helpers

    /// Builds the date the parser is expected to produce: same pattern,
    /// en_US_POSIX, the device's current timezone (both Clarity and LibreView
    /// timestamps are zone-less local times).
    private func localDate(_ string: String, pattern: String, line: UInt = #line) -> Date {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = .current
        formatter.dateFormat = pattern
        guard let date = formatter.date(from: string) else {
            XCTFail("test fixture date '\(string)' didn't parse", line: line)
            return .distantPast
        }
        return date
    }

    // MARK: Format detection

    func testDetectsEachKnownFormat() {
        XCTAssertEqual(ExternalCSVImporter.detectFormat(clarityMgdl), .dexcomClarity)
        XCTAssertEqual(ExternalCSVImporter.detectFormat(clarityMmol), .dexcomClarity)
        XCTAssertEqual(ExternalCSVImporter.detectFormat(libreViewUS), .libreView)
        XCTAssertEqual(ExternalCSVImporter.detectFormat(libreViewEU), .libreView)
        XCTAssertEqual(ExternalCSVImporter.detectFormat(prvitalCSV), .prvital)
    }

    func testUnknownFilesAreRejected() {
        XCTAssertNil(ExternalCSVImporter.detectFormat("Name,Email\nJane Doe,jane@example.com"))
        XCTAssertNil(ExternalCSVImporter.detectFormat(""))
        XCTAssertNil(ExternalCSVImporter.detectFormat("just some prose, not a header"))
        XCTAssertNil(ExternalCSVImporter.parse("Name,Email\nJane Doe,jane@example.com")?.format)
    }

    // MARK: Dexcom Clarity

    func testClarityMgdlDocumentDecodesEveryRecordKind() throws {
        let (format, result) = try XCTUnwrap(ExternalCSVImporter.parse(clarityMgdl))
        XCTAssertEqual(format, .dexcomClarity)
        XCTAssertEqual(result.rows.count, 6)
        XCTAssertEqual(result.skipped, 0, "account/device/alert metadata rows must not count as skipped")

        let first = result.rows[0]
        XCTAssertEqual(first.record, .glucose(mgdL: 124, measurement: .cgm, trend: nil))
        XCTAssertEqual(first.source, .dexcom)
        XCTAssertEqual(first.timestamp,
                       localDate("2024-06-01T08:03:12", pattern: "yyyy-MM-dd'T'HH:mm:ss"))

        XCTAssertEqual(result.rows[2].record,
                       .insulin(units: 4.5, type: .rapidActing, context: .mealBolus, name: nil))
        XCTAssertEqual(result.rows[3].record,
                       .insulin(units: 18.0, type: .longActing, context: .basal, name: nil))
        XCTAssertEqual(result.rows[4].record,
                       .carbs(grams: 45, meal: .lunch, food: nil),
                       "12:30 carbs infer Lunch from the hour")
        XCTAssertEqual(result.rows[5].record,
                       .glucose(mgdL: 118, measurement: .calibration, trend: nil))
    }

    func testClarityMmolConvertsToMgdL() throws {
        let (_, result) = try XCTUnwrap(ExternalCSVImporter.parse(clarityMmol))
        guard case let .glucose(mgdL, measurement, trend)? = result.rows.first?.record else {
            return XCTFail("expected a glucose record")
        }
        XCTAssertEqual(mgdL, 6.9 * GlucoseUnit.conversionFactor, accuracy: 1e-6)
        XCTAssertEqual(measurement, .cgm)
        XCTAssertNil(trend)
    }

    func testClarityLowHighClampsAreSkipped() throws {
        let (_, result) = try XCTUnwrap(ExternalCSVImporter.parse(clarityWithClamps))
        XCTAssertEqual(result.rows.count, 1, "only the numeric EGV survives")
        XCTAssertEqual(result.rows.first?.record, .glucose(mgdL: 250, measurement: .cgm, trend: nil))
        XCTAssertEqual(result.skipped, 2, "'Low' and 'High' clamp rows count as skipped")
    }

    // MARK: LibreView

    func testLibreViewUSDocumentDecodesEveryRecordKind() throws {
        let (format, result) = try XCTUnwrap(ExternalCSVImporter.parse(libreViewUS))
        XCTAssertEqual(format, .libreView)
        XCTAssertEqual(result.rows.count, 7)
        XCTAssertEqual(result.skipped, 1, "the notes row (Record Type 6) counts as skipped")

        let first = result.rows[0]
        XCTAssertEqual(first.record, .glucose(mgdL: 101, measurement: .cgm, trend: nil))
        XCTAssertEqual(first.source, .freeStyleLibre)
        XCTAssertEqual(first.timestamp,
                       localDate("06-01-2024 08:04 AM", pattern: "MM-dd-yyyy hh:mm a"))

        XCTAssertEqual(result.rows[2].record,
                       .glucose(mgdL: 112, measurement: .cgm, trend: nil),
                       "a scan (Record Type 1) is still a sensor reading")
        XCTAssertEqual(result.rows[3].record,
                       .insulin(units: 6.5, type: .rapidActing, context: .mealBolus, name: nil))
        XCTAssertEqual(result.rows[4].record,
                       .insulin(units: 22, type: .longActing, context: .basal, name: nil))
        XCTAssertEqual(result.rows[5].record,
                       .carbs(grams: 52, meal: .lunch, food: nil),
                       "12:20 PM food infers Lunch from the hour")
        XCTAssertEqual(result.rows[6].record,
                       .glucose(mgdL: 98, measurement: .fingerstick, trend: nil),
                       "a strip value (Record Type 2) is a fingerstick reading")
    }

    func testLibreViewEUDateFormatAndMmolConversion() throws {
        let (_, result) = try XCTUnwrap(ExternalCSVImporter.parse(libreViewEU))
        XCTAssertEqual(result.rows.count, 2)
        XCTAssertEqual(result.skipped, 0)

        guard case let .glucose(mgdL, _, _)? = result.rows.first?.record else {
            return XCTFail("expected a glucose record")
        }
        XCTAssertEqual(mgdL, 6.1 * GlucoseUnit.conversionFactor, accuracy: 1e-6)

        // "13-06-2024 14:19" only fits day-month, so the whole document must
        // have been parsed with the EU pattern in the current timezone.
        let components = Calendar.current.dateComponents(
            [.year, .month, .day, .hour, .minute], from: result.rows[1].timestamp
        )
        XCTAssertEqual(components.year, 2024)
        XCTAssertEqual(components.month, 6)
        XCTAssertEqual(components.day, 13)
        XCTAssertEqual(components.hour, 14)
        XCTAssertEqual(components.minute, 19)
    }

    // MARK: Prvital routing

    func testPrvitalExportRoutesThroughExistingParser() throws {
        let (format, result) = try XCTUnwrap(ExternalCSVImporter.parse(prvitalCSV))
        XCTAssertEqual(format, .prvital)
        XCTAssertEqual(result.rows.count, 1)
        XCTAssertEqual(result.skipped, 0)
        XCTAssertEqual(result.rows.first?.record, .glucose(mgdL: 124, measurement: .cgm, trend: nil))
    }
}
